/* $Id$ */

/*
 * ``Poor Man's LOAD''
 * list of functions loaded with snobol4 image.
 *
 * See lib/snolib/*.c for example functions
 */

/*
 * NOTE!! PMLFUNC2 used for exntry points renamed due to 
 * name collisions (many due to VMS config.h define games)
 */

#ifndef NO_PML_HOST
PMLFUNC(HOST)				/* SPITBOL compat */
PMPROTO("HOST()")			/* two polymorphic params */
#endif /* NO_PML_HOST not defined */

#ifndef NO_PML_EXIT
PMLFUNC2("EXIT",EXIT)			/* SPITBOL compat */
PMPROTO("EXIT()")			/* one polymorphic param */
#endif /* NO_PML_EXIT not defined */

#ifndef NO_PML_REAL
#ifndef NO_PML_SQRT
PMLFUNC2("SQRT",SQRT)
PMPROTO("SQRT(REAL)REAL")
#endif /* NO_PML_SQRT not defined */

#ifndef NO_PML_EXP
PMLFUNC2("EXP",EXP)
PMPROTO("EXP(REAL)REAL")
#endif /* NO_PML_EXP not defined */

#ifndef NO_PML_LOG
PMLFUNC2("LOG",LOG)
PMPROTO("LOG(REAL)REAL")
#endif /* NO_PML_LOG not defined */

#ifndef NO_PML_CHOP
PMLFUNC(CHOP)
PMPROTO("CHOP(REAL)REAL")
#endif /* NO_PML_CHOP not defined */

#ifndef NO_PML_TRIG
PMLFUNC2("SIN",SIN)
PMPROTO("SIN(REAL)REAL")

PMLFUNC2("COS",COS)
PMPROTO("COS(REAL)REAL")

PMLFUNC2("TAN",TAN)
PMPROTO("TAN(REAL)REAL")
#endif /* NO_PML_TRIG not defined */
#endif /* NO_PML_REAL not defined */

#ifndef NO_PML_FILE
PMLFUNC2("FILE",FILE2)			/* SITBOL compat */
PMPROTO("FILE(STRING)STRING")
#endif /* NO_PML_FILE not defined */

#ifndef NO_PML_DELETE
PMLFUNC2("DELETE",DELETE)		/* SITBOL compat */
PMPROTO("DELETE(STRING)STRING")
#endif /* NO_PML_DELETE not defined */

#ifndef NO_PML_RENAME
PMLFUNC2("RENAME",RENAME)		/* SITBOL compat */
PMPROTO("RENAME(STRING)STRING")
#endif /* NO_PML_RENAME not defined */

/* 4/7/97; */
PMLFUNC2("IO_FINDUNIT",IO_FINDUNIT)
PMPROTO("IO_FINDUNIT()INTEGER")

/* experimental 3/12/99; */
PMLFUNC(SSET)
PMPROTO("SSET(INTEGER,INTEGER,INTEGER,INTEGER)INTEGER")

/* 4/27/2001; */
#ifdef PML_SERV
PMLFUNC(SERV_LISTEN)
PMPROTO("SERV_LISTEN(STRING,STRING,STRING)INTEGER")
#endif /* PML_SERV defined */

/* 12/6/2001; */
PMLFUNC(ORD)
PMPROTO("ORD(STRING)INTEGER")

/* 1/21/2002; */
PMLFUNC(LOGIC)
/* LOAD() in logic.sno */

/* 6/19/2004; */
#ifdef PML_COM
PMLFUNC(COM_LOAD)
PMPROTO("COM_LOAD(STRING)INTEGER")

PMLFUNC(COM_INVOKE)
PMPROTO("COM_INVOKE(INTEGER,STRING)")

PMLFUNC(COM_GETPROP)
PMPROTO("COM_GETPROP(INTEGER,STRING)")

PMLFUNC(COM_PUTPROP)
PMPROTO("COM_PUTPROP(INTEGER,STRING,)STRING")

PMLFUNC(COM_RELEASE)
PMPROTO("COM_RELEASE(INTEGER)STRING")
#endif

/* 8/25/2004; */
#ifdef PML_STCL
PMLFUNC(STCL_CREATEINTERP)
PMPROTO("STCL_CREATEINTERP()INTEGER")
PMLFUNC(STCL_EVALFILE)
PMPROTO("STCL_EVALFILE(INTEGER,STRING)STRING")
PMLFUNC(STCL_GETVAR)
PMPROTO("STCL_GETVAR(INTEGER,STRING)STRING")
PMLFUNC(STCL_SETVAR)
PMPROTO("STCL_SETVAR(INTEGER,STRING,STRING)STRING")
PMLFUNC(STCL_EVAL)
PMPROTO("STCL_EVAL(INTEGER,STRING)STRING")
PMLFUNC(STCL_DELETEINTERP)
PMPROTO("STCL_DELETEINTERP(INTEGER)STRING")
/* New: 9/1/2004 */
PMLFUNC(STCL_NEWSTRINGOBJ)
PMPROTO("STCL_NEWSTRINGOBJ(STRING)INTEGER")
PMLFUNC(STCL_GETSTRINGFROMOBJ)
PMPROTO("STCL_GETSTRINGFROMOBJ(INTEGER)STRING")
PMLFUNC(STCL_APPENDTOOBJ)
PMPROTO("STCL_APPENDTOOBJ(INTEGER,STRING)STRING")
PMLFUNC(STCL_EVALOBJEX)
PMPROTO("STCL_EVALOBJEX(INTEGER,INTEGER,INTEGER)STRING")
PMLFUNC(STCL_GETOBJRESULT)
PMPROTO("STCL_GETOBJRESULT(INTEGER)")
PMLFUNC(STCL_OBJSETVAR2)
PMPROTO("STCL_OBJSETVAR2(INTEGER,STRING,STRING,INTEGER,INTEGER)STRING")
PMLFUNC(STCL_OBJGETVAR2)
PMPROTO("STCL_OBJGETVAR2(INTEGER,STRING,STRING,INTEGER)STRING")
PMLFUNC(STCL_RELEASEOBJ)
PMPROTO("STCL_RELEASEOBJ(INTEGER)STRING")
#endif

#ifdef PML_NDBM
PMLFUNC2(DBM_OPEN,DBM_OPEN)
PMPROTO("DBM_OPEN(STRING,STRING,STRING)INTEGER")
PMLFUNC2(DBM_CLOSE,DBM_CLOSE)
PMPROTO("DBM_CLOSE(INTEGER)STRING")
PMLFUNC2(DBM_STORE,DBM_STORE)
PMPROTO("DBM_STORE(INTEGER,STRING,STRING,INTEGER)INTEGER")
PMLFUNC2(DBM_FETCH,DBM_FETCH)
PMPROTO("DBM_FETCH(INTEGER,STRING)STRING")
PMLFUNC2(DBM_FIRSTKEY,DBM_FIRSTKEY)
PMPROTO("DBM_FIRSTKEY(INTEGER)STRING")
PMLFUNC2(DBM_NEXTKEY,DBM_NEXTKEY)
PMPROTO("DBM_NEXTKEY(INTEGER)STRING")
PMLFUNC2(DBM_DELETE,DBM_DELETE)
PMPROTO("DBM_DELETE(INTEGER,STRING)INTEGER")
#endif
