#!/bin/sh
# $Id$

# perform basic timing tests
# results suitable for inclusion in ports.doc
# pb 6/4/94

echo 'Date:'
date
echo ''
echo 'who am i:'
who am i
echo ''
echo 'uname -a:'
uname -a
echo ''
echo 'config.guess:'
./config.guess
echo ''
echo 'ls -l config.m4 xsnobol4:'
ls -l config.m4 xsnobol4
echo ''
echo 'config.m4:'
cat config.m4
echo ''
echo 'size xsnobol4:'
size xsnobol4

if [ -x /usr/bin/uptime ]; then
	echo ''
	echo 'uptime:'
	/usr/bin/uptime
elif [ -x /usr/ucb/uptime ]; then
	echo ''
	echo 'uptime:'
	/usr/ucb/uptime
fi

echo ''
echo 'timing run of genc.sno:'

TDIR=timdir.$$
(
	rm -rf $TDIR
	mkdir $TDIR
	cd $TDIR
LNFILES='../xsnobol4 ../procs ../globals ../v311.sil ../genc.sno ../snobol4.c'
# AFS doesn't allow hard links across directories!
	ln $LNFILES . || ln -s $LNFILES .
	
# NOTE! 2>&1 *BEFORE* >x
	time ./xsnobol4 -s genc.sno 2>&1 >x
	echo ==== diff
	diff snobol4.c x

	cd ..
	rm -rf $TDIR
) | ./xsnobol4 -b timing.sno
# NOTE: do not add commands here; xsnobol4 exit status is shell exit status!!
