#!/bin/sh
# $Id$

# perform basic timing tests
# pb 6/4/94

if [ "$*" ]; then
	SNOBOL=$1
	shift
	ARGS="$*"
else
	SNOBOL=./xsnobol4
fi

echo 'Date:'
date
echo ''
for p in `echo $PATH | tr : ' '`; do
	if [ -f $p/uname ]; then
		UNAME=$p/uname
		break
	fi
done
if [ "$UNAME" ]; then
	echo 'uname -a:'
	$UNAME -a
	echo ''

	# show hardware, if we know how;
	case `$UNAME` in
	AIX*)
		echo /usr/sbin/lsattr -EHl proc0
		/usr/sbin/lsattr -EHl proc0 2>&1
		echo ''
		;;
	*BSD*)
		if [ -x /usr/sbin/sysctl ]; then
			echo /usr/sbin/sysctl hw:
			/usr/sbin/sysctl hw 2>/dev/null
			echo ''
		elif [ -x /sbin/sysctl ]; then
			echo /sbin/sysctl hw:
			/sbin/sysctl hw 2>/dev/null
			echo ''
		fi
		;;
	HP-UX)
		if [ -f /usr/bin/model ]; then
			echo /usr/bin/model:
			/usr/bin/model
			echo ''
		elif [ -f /bin/model ]; then
			echo /bin/model:
			/bin/model
			echo ''
		fi
		;;
	IRIX*)
		echo 'hinv:'
		hinv
		echo ''
		;;
	Linux)
		if [ -f /proc/cpuinfo ]; then
			echo /proc/cpuinfo:
			cat /proc/cpuinfo
			echo ''
		fi
		if [ -f /proc/meminfo ]; then
			echo /proc/meminfo:
			cat /proc/meminfo
			echo ''
		fi
		;;
	SunOS)
		echo 'sunmodel:'
		./sunmodel 2>&1
		echo ''
		if [ -f /usr/sbin/psrinfo ]; then
			echo 'psrinfo -v:'
			/usr/sbin/psrinfo -v
		fi
		;;
	esac
fi
#
echo 'config.guess:'
./config.guess
echo ''
echo "ls -l config.m4 ${SNOBOL}:"
ls -l config.m4 $SNOBOL
echo ''
echo 'config.m4:'
cat config.m4
echo ''
if [ "$CCVERS" ]; then
	echo "$CC $CCVERS"
	$CC $CCVERS
	echo ''
fi
echo "size ${SNOBOL}:"
size $SNOBOL

if [ -x /usr/bin/uptime ]; then
	echo ''
	echo 'uptime:'
	/usr/bin/uptime
elif [ -x /usr/ucb/uptime ]; then
	echo ''
	echo 'uptime:'
	/usr/ucb/uptime
fi

echo ''
echo 'timing run of genc.sno:'
if [ "$ARGS" ]; then
	echo "	args: $ARGS"
fi

# stdout redirection fails with built in "time" (OpenBSD, AIX4)
if [ -x /usr/bin/time ]; then
	TIME=/usr/bin/time
elif [ -x /usr/5bin/time ]; then
	TIME=/usr/5bin/time
else
	TIME=time
fi

# run genc in a subdirectory to avoid trashing generated files!

TDIR=timdir.$$
rm -rf $TDIR
trap "rm -rf $TDIR; exit 1" 1 2 15
mkdir $TDIR
OUT=stdout
TAIL1='sed -n 2,$p'
(
	ln $SNOBOL $TDIR/snobol4 || ln -s $SNOBOL $TDIR/snobol4

	cd $TDIR

LNFILES='../procs ../globals ../v311.sil'
# AFS doesn't allow hard links across directories!
	ln $LNFILES . || ln -s $LNFILES .

	# stderr to file "stderr", all but first line of stdout to "$OUT"
	$TIME ./snobol4 $ARGS -s ../genc.sno v311.sil 2>stderr | $TAIL1 >$OUT
)
# use snobol program to process output!!
$SNOBOL -b timing.sno < $TDIR/stderr
# save exit status
STAT=$?

# check output regardless of timing.sno status
if $TAIL1 < snobol4.c | cmp -s - $TDIR/$OUT; then
	echo "genc.sno output checks out"
	rm -rf $TDIR
else
	echo "ERROR: genc.sno output is bad; compare $TDIR/$OUT with snobol4.c"
	STAT=2
fi

exit $STAT
