MOD=jsmn

all install clean test debug test_verbose:
	$(MAKE) -f ../Makefile.mod $@ MOD=$(MOD) SRC="jsmn.c funcs.sno"

# curl https://raw.githubusercontent.com/zserge/jsmn/refs/heads/master/jsmn.h > jsmn.h
