# New ports collection makefile for:	snobol4
# Version required:	1.0
# Date created:		18 February 2004
# Whom:			Phil Budne <phil@ultimate.com>
#
# $Id$
#

DISTNAME=	snobol4-1.0
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.snobol4.org/snobol/

MAINTAINER=	phil@ultimate.com

HAS_CONFIGURE=		yes
CONFIGURE_SCRIPT=	configure
CONFIGURE_ARGS+=	--prefix=${PREFIX}

.include <bsd.port.mk>
