.\" -*-nroff-*-
.\" $Id$
.TH SNOBOL4 1 "22 October 1996" "Local"
.SH NAME
snobol4 \- SNOBOL4 interpreter
.SH SYNOPSIS
.B snobol4
[
.I options
\&.\|.\|.
]
[
.I file(s)
\&.\|.\|.
]
[
.I params
\&.\|.\|.
]

.SH DESCRIPTION
.PP
This manual page describes a port of the original Bell Telephone Labs
(BTL) Macro Implementation of SNOBOL4 (MAINBOL) to machines with
32-bit C compilers by Philip L. Budne.  The language and it's
implementation are described in [1] and [2].  Extensions from Catspaw
SNOBOL4+, SPITBOL and SITBOL have been added.

.SS Limitations
.PP
All aspects of the language are implemented except;
.IP \(bu
Trapping of arithmetic exceptions.
.IP \(bu
Dynamic use of the
.B LOAD()
platforms not using
.BR a.out (5)
executable format is not supported. User functions can be staticly
linked (poor man's loading) on
.B ALL
platforms.  See load.doc for more information.

.SS "Changes"
.PP
The following behaviors have been changed;
.IP \(bu
Listings are disabled by default.
Default listing side (when enabled by
.BR -LIST
or the
.B -l
option is
.BR LEFT .
Listings are directed to standard output.
.IP \(bu
Error messages, the startup banner and statistics are directed to
standard error.  Compilation error messages (including erroneous
lines) appear on standard error as well as in the listings.  Error
messages now reference the source file name and line number.
.IP \(bu
Character set (see below).
.IP \(bu
The
.B PUNCH
output variable no longer exists (see
.B TERMINAL
variable below).
.IP \(bu
I/O is not performed using FORTRAN I/O.  The 3rd argument to the
.B OUTPUT()
and
.B INPUT()
functions are interpreted as a string of I/O options (see below).
.IP \(bu
Control lines and comment characters are valid after the end of string
(;) statement separator.  Listing statement numbers show the statement
number of the LAST statement on the line (rather than the first).
.IP \(bu
Setting the
.B &ABEND
keyword causes a core dump upon termination!
.IP \(bu
The value of the
.B &CODE
keyword determines the exit status of the
.B snobol4
application.
.IP \(bu
The
.B DATE()
function returns strings of the form:
.I "MM/DD/YYYY HH:MM:SS"
.IP \(bu
Keyword
.B &STLIMIT
now defaults to -1.
When
.B &STLIMIT
is less than zero
there is no limit to the number of statements execute, and
.B &STCOUNT
is not incremented.
.IP \(bu
.B VALUE
tracing applies to variables modified by immediate value assignment ($
operator) and value assignment (. operator) during pattern matching.
.IP \(bu
The
.B BACKSPACE()
function is not implemented. See
.B SET()
below.

.SS "Character set"
.PP
The internal character set and collating sequence are USASCII-8.  Any
8-bit byte pattern is accepted as a SNOBOL datum or in a string
constant of a SNOBOL source program.  The value of the SNOBOL
protected keyword
.B &ALPHABET
is a 256-character string of all Bytes from 0 to 255, in ascending
order.  Programs may be entered in mixed case.  By default lower case
identifiers are folded to upper case (see
.B &CASE
and
.B \-CASE
extensions).
.PP
The following operator character sequences are permitted and represent
a cross between PDP-10 MAINBOL (a.k.a. DECBOL), SITBOL and Catspaw
SPITBOL usage;

.ta 2i
.nf
Exponentiation:	^\0**
Alternation:	|\0!
Unary negation:	~\0\\
Assignment:	=\0_
Comment line:	*\0#\0|\0;\0!
Continuation line:	+\0.
.fi
.PP
Both brackets ([]) and angle-brackets (<>) may be used to subscript
arrays and tables.  The
.B TAB
(ASCII 9) character is accepted as whitespace.  Note that the use of
the pound sign for comments allows use of the shell interpreter
sequence at the top of a file (ie; "#!/usr/local/bin/snobol4 -b").
Underscore (_) and period (.) are legal within identifiers and labels.

.SS "Extensions"
.TP
.BR "ARRAY/TABLE " access
.br
Multiple
.B ARRAY
and/or
.B TABLE
index operations may appear in a row,
without having to resort to use of the
.B ELEMENT
function, so long as no intervening spaces (or line continuations) appear.
.TP
.B BREAKX()
.br
The
.B BREAKX()
function is a pattern function used for fast scanning.
\fBBREAKX(\fIstr\fB)\fR is equivalent to \fBBREAK(\fIstr\fB)
ARBNO(LEN(1) BREAK(\fIstr\fB))\fR.  In other words BREAKX matches a
sequence of ever larger strings terminated by a break set.  BREAKX can
be used as a faster matching replacement for
.B ARB
since
.B "BREAKX('S') 'STRING'"
always runs faster than
.B "ARB 'STRING'"
since it only attempts matching
.B "'STRING'"
when an
.B "'S'"
has been detected.

.TP
Case folding
.br
By default the compiler folds identifiers and directives
to upper case, so programs can be entered in either case.  To disable
case folding use the directive
.B "\-CASE 0" or
.BR "\-CASE" .
To re-enable case folding use directive
.BI "\-CASE " n
where
.I n
is a non-zero integer.  The status of case folding may be examined and
controlled from a running program by the unprotected system keyword
.BR &CASE .
.TP
.B CHAR()
.br
The
.B CHAR()
function takes an integer from 0 to 255 and returns the n'th character
in
.B &ALPHABET .
.TP
.B \-ERROR/\-NOERRORS
.br
Directives
.B \-ERROR
and
.B \-NOERRORS
control execution of program with compiler errors.  If the
.B \-ERROR
directive is given, the program will be executed (but any attempt to
execute a statement with a compiler error will cause a fatal execution
error).  By default programs with compiler errors will not be started,
this can be restored using
.BR \-NOERRORS .
.TP
.B &ERRTEXT
.br
After an otherwise fatal error is curtailed due to a non-zero value in
.BR &ERRLIMIT ,
the protected keyword
.B &ERRTEXT
will contain the error message.
.TP
.B \-EXECUTE/\-NOEXECUTE
.br
Directives
.B \-EXECUTE
and
.B \-NOEXECUTE
control execution of programs.  If the
.B \-NOEXECUTE
directive is given, the program will be not executed after compilation.
.B \-EXECUTE 
Cancels any previous
.BR \-NOEXECUTE .
.TP
.B FREEZE()/THAW()
.br
The
.B FREEZE()
function prohibits new entry creation in the referenced table.  This
is useful once a table has been initialized to avoid the creation of
empty entries that normally occurs on table entry lookup failure. This
can greatly improve program speed, since frozen tables will not become
clogged with random entries. Lookups for uninitialized entries will
return the null string, however attempts to create a new entry will
cause a \*(lqVariable not present where required\*(rq error. The
.B THAW()
function restores normal entry creation behavior.
.TP
.B HOST()
.br
A limited simulation of the SPITBOL
.B HOST()
function is included.  It does not perform argument type conversions,
so all arguments must be supplied as either
.B INTEGER
or
.B STRING
data types.

.br
.B HOST()
with no parameters returns a string describing the system the program
is running on.  The string contains three parts, separated by colons.
The first part describes the physical architecture, the second
describes the operating system, and the third describes the language
implementation name. Example:
.I "sun4c:SunOS 4.1.4:C-MAINBOL 0.98.3"

.br
.B HOST(0)
returns a string containing the command line parameter supplied to the
.B -u
option, if any.  If no
.B -u
option was given,
.B HOST(0)
returns the concatenation of all user parameters following the input
filename(s).

.br
\fBHOST(1,\fIstring\fB)\fR passes the string to the
.BR system (3)
c library function, and returns the subprocess exit status.

.br
\fBHOST(2,\fIn\fB)\fR for integer
.I n
returns the
.IR n "'th"
command line argument (regardless of whether the argument
was the command name, an option, a filename or a user parameter)
as a string, or failure if
.I n
is out of range.

.br
.B HOST(3)
returns an integer for use with
.B HOST(2)
indicating the first command line argument available as a user parameter.

.br
\fBHOST(4,\fIstring\fB)\fR returns the value of the
environment variable named 
.IR string .
.TP
.B \-INCLUDE
.br
The
.B \-INCLUDE 
directive causes the compiler to interpolate the contents of the named
file enclosed in single or double quotes.  Any filename will be
included only once, this can be overridden by appending a trailing
space to the filename.  Trailing spaces are removed from the filename
before use.  If the file is not found in the current working directory
an attempt will be made to find it in the directory specified by the
.B SNOLIB
environment variable, or if that is not set, a predetermined library
directory.

.br
.B \-COPY
is a synonym for
.B \-INCLUDE
for compatibility with SPITBOL/370.
.TP
.B &LINE/&FILE
.br
The
.B &LINE
and
.B &FILE
keywords can be used to determine the source file and file line
associated with the current statement.  The
.B &LASTLINE
and
.B &LASTFILE
return the source file and file line
associated with the previous statement.
.TP
.B \-LINE
.br
The
.B \-LINE
directive can be used to alter SNOBOL's idea of the current source
file and line (ie; for use by preprocessors).
.B \-LINE
takes a line number and an optional quoted string filename.
.TP
Lexical comparison
.br
A full set of lexical (string) comparison predicates
have been added to complement the standard
.B LGT()
function;
.BR LEQ() ,
.BR LGE() ,
.BR LLE() ,
.BR LLT() ,
.BR LNE() .
.TP
.B LPAD()/RPAD()
.br
The
.B LPAD()
and
.B
.B RPAD()
functions take the first argument (subject) string, and pad it out to
the length specified in the second argument, using the first character
of the optional third argument.  If the third argument is missing, or
is the null string. spaces will be used for padding.  The subject will
be returned unmodified if already long enough.
.TP
Named files
.br
Filenames
can be supplied to the
.B INPUT()
and
.B OUTPUT()
functions via an optional fourth argument.  If the filename begins
with a vertical bar (|), the remainder is used as a shell command
whose stdin (in the case of
.BR OUTPUT() )
or stdout (in the case of
.BR INPUT() )
will be connected to the file variable.  The filename - (hypen) is
interpreted as stdin on
.B INPUT()
and stdout
on
.BR OUTPUT() .
The magic filenames
.BR /dev/stdin ,
.BR /dev/stdout ,
and
.B /dev/stderr
refer to the current process standard input, standard output and
standard error respectively regardless of whether those special
filenames exist on your system.  The magic pathname
\fB/tcp/\fIhostname\fB/\Iservice\fR can be used to open connection
to a TCP server. If the path ends in
.B /priv
the connection will be originated from a privileged local port using
.BR rresvport (3).
.TP
.B &PARM
.br
The entire command line is available via the
.BR &PARM
protected keyword for compatibility with Catspaw SNOBOL4+. Use of the
SPITBOL compatible
.B HOST()
function is probably preferable.
.TP
.B REVERSE()
.br
.B REVERSE()
returns it's subject string in reverse order.
.TP
Scientific notation
.br
.B REAL
number syntax has been expanded to allow exponents
of the form:
.br
.IR "ANY('DeEe') ('+' | '-' | '') SPAN('0123456789')" .
.TP
.B SET()
.br
The
.B SET()
function can be used to seek the file pointer of an open file.  The
first argument is an I/O unit number, the second is an integer offset.
The third argument, an integers determins from
.B whence
the file pointer will be adjusted.  If whence is zero the starting
point is the begining of the file, if whence is one, the starting
point is the current file pointer, and if whence is two, the starting
point is the end of the file.
.B SET()
returns the new file pointer value.
.TP
SITBOL file functions
.br
\fBFILE(\fIstring\fB)\fR is a predicate which returns the null string
if it's argument is the name of a file that exists, and fails if it
does not.  \fBDELETE(\fIstring\fB)\fR is a predicate which tries to
remove the file named by it's argument, and fails if it cannot.
\fBRENAME(\fIstring1\fB,\fIstring2\fB)\fR 
is a predicate which attempts to rename the file named by
.I string2
to the file named by
.IR string1 .
Unlike the SITBOL version, if the target file exists, it will be
removed.
.TP
SNOBOL4+ real functions
.br
.BR EXP() ,
.B LOG()
and
.B CHOP() 
functions are available for compatibility with SNOBOL4+.
.B EXP()
returns the value
.IR "e ** x" ,
.B LOG()
returns the natural logarithm of it's argument, and
.B CHOP()
truncates the fractional part of it's (rounding towards zero), and
returns a real.
.TP
.B SORT()/RSORT()
.br
The
.B SORT()
and
.B
.B RSORT()
functions take a array (or table, which is first converted to an
array). The array may be singly-dimensioned if which case , if non-
null, will indicate the field of a programmer-defined data type on which
the sort is based.  A may also be a table or a doubly-dimensioned
array.  In these cases F may be an integer indicating the column on
which to sort.  If F is null, it is taken to be 1.  The array A is not
modified; a new array is allocated and returned.
.B SORT()
sorts elements in ascending order, while
.B RSORT()
sorts in descending order.
.TP
SPITBOL operators
.br
The SPITBOL scan (?) and assignment (=) operators have been added.  A
pattern match can appear within an expression, and returns the matched
string as it's value.  Similarly assignment can appear in an
expression, and returns the assigned value. An assignment after a scan
(ie;
.IR "STRING ? PATTERN = VALUE" )
performs a scan and replace.  Assignment is right associative, and has
the lowest precedence, while scan is left associative and has a
precedence just higher than assignment.

.br
The SPITBOL selection/alternative construction can be used in any
expression.  It consists of a comma separated list of expressions
inside parentheses.  The expressions are evaluated until one succeeds,
and it's value is returned.  Abuse of this construction may result in
incomprehensible code.

.br
The type
.B NUMERIC
with
.B CONVERT()
and the removal of leading spaces from strings converted to numbers
(implicitly or explicitly) are also legal when SPITBOL extensions are
enabled.  SPITBOL extensions can be enabled and disabled using the
.B "\-PLUSOPS"
directive.
.B "\-PLUSOPS 0"
disables SPITBOL operators, while
.B "\-PLUSOPS" 
or
.BI "\-PLUSOPS " n
where
.I n
is a non-zero integer enables them.  SPITBOL extensions are enabled by
default.
.TP
.BR SQRT()
.br
The
.BR SQRT()
function is available for compatibility with SPARC SPITBOL.  
.BR SQRT()
fails if the argument is negative, but does not cause a fatal error.
.TP
.B SUBSTR()
.br
.B SUBSTR()
takes a subject string as it's first argument, and returns the substring
starting at the position specified by the second argument (one-based) with
a length specified by the third argument.  If the third argument is missing
or zero, the remainder of the string is returned.
.TP
.BR "TERMINAL " "I/O variable"
.br
The variable
.B TERMINAL
is associated with the standard error file descriptor for both input
and output.
.TP
Trig functions
.br
.BR SIN() ,
.B COS()
and
.B TAN()
functions are available for compatibility with SPARC SPITBOL
and take arguments in radians.
.TP
.B &UCASE/&LCASE
.br
Protected keywords
.B &UCASE
and
.B &LCASE
contain upper and lower case characters respectively.

.SS "I/O Associations"
.PP
I/O is performed by associating a variable name with a numbered I/O
unit using the
.B INPUT()
and
.B OUTPUT()
functions.  The following associations are available by default;

.br
.ta 1i 2i
.nf
Variable	Unit	Association
\fBINPUT\fR	5	standard input
\fBOUTPUT\fR	6	standard output
\fBTERMINAL\fR	7	standard error (output)
\fBTERMINAL\fR	8	standard error (input)
.fi

.SS "I/O Options"
.PP
The third argument of the
.B INPUT()
and
.B OUTPUT()
functions is interpreted as a string of single letter options, commas
are ignored.  Some options effect only the I/O variable named in the
first argument, others effect any variable associated with the unit
number in the second argument.
.TP
.I digits
A span of digits will set the input record length for the named I/O
variable.  This controls the maximum string that will be returned for
regular text I/O, and the number of bytes returned for binary I/O.
Record length is per-variable; multiple variables may be associated
with the same unit, but with different record lengths.
.TP
.B A
The unit will be opened for append access in
for
.BR OUTPUT()
(noop for
.BR INPUT() ).
.TP
.B B
The unit will be opened for binary access.  On input newline
characters have no special meaning; the number of bytes transferred
deppends on record length (see above). On output no newline is
appended.  For terminal devices, all I/O to this unit will be
performed in
.I cbreak
mode, however I/O on other units continues to perform I/O in
.I cooked
mode.
.TP
.B C
Character at a time I/O.  A synonym for
.BR "B,1" .
.TP
.B T
Terminal mode.  No newline characters are added on output, and any
newline characters are returned on input.  Terminal mode effects only
the referenced unit.  Terminal mode is useful for outputting prompts
in interactive programs.
.TP
.B Q
Quiet mode.  Turns off input echo on terminals.  Effects only input
from this unit.
.TP
.B U
Update mode.  The unit is opened for both input and output.
.TP
.B W
Unbuffered writes.  Each output variable assignment causes
an I/O transfer to occur.

.SH OPTIONS
.TP 1i
.B \-b
Toggle startup banner output (by default on).
.TP
.BI "-d " NNN
Allocate
.I NNN
bytes of \*(lqdynamic storage\*(rq for program code and data. A suffix
of
.B k
multiplies the number by 1024. A larger dynamic region may result in
fewer garbage collections (storage regenerations), however large
values may cause collections (when they occur) to run more slowly.
Most programs do not need an increased dynamic region to run.  If your
program terminates with a \*(lqInsufficient storage to continue\*(rq
message you need to increase the dynamic storage region size.
.TP
.B -f
Toggle folding of identifiers to upper case (see
.B \-CASE
and
.BR &CASE ).
.TP
.B -h
Give help. Shows usage message, includes default sizes for
\*(lqdynamic region\*(rq and pattern match stack.
.TP
.B -k
Toggle running programs with compilation errors (see
.B \-ERROR
and
.B \-NOERRORS
extensions).  By default programs with compilation errors will not be
run.
.TP
.B -l
Re-enable listing to stdout.  (default is
.BR \-UNLIST ).
Default listing side is
.BR LEFT .
.TP
.B -n
Toggle running programs after compilation (see
.B \-EXECUTE
and
.B \-NOEXECUTE
extensions).  By default programs are run after compilation.
.TP
.B -p
Toggle SPITBOL extensions (also controlled by
.BR \-PLUSOPS ).
.TP
.B -r
Toggle reading
.B INPUT
from input file(s) after
.B END
label.  Otherwise
.B INPUT
defaults (back) to standard input after program compilation is complete.
.TP
.B -s
Toggle termination statistics (off by default).
.TP
.BI "-u " params
specifies a parameter string available via
.BR "HOST(0)" .
.TP
.B --
Terminates processing items as options. Any remaining strings are
treated as files or user parameters.
.TP
.B -M
Specifies that all items left on the command line after option
processing is complete are to be treated as filenames.  The files
are read in turn until an
.B END
statement is found (Any remaining data is available via the
.B INPUT
variable if
the
.B -r
option is also given).
A
.B --
terminates processing of arguments as files, and makes the remaining
arguments available as user parameters (see the
.B HOST()
function).
.TP
.BI "-P " NNN
Allocate
.I NNN
bytes of memory for the pattern match stack.  A suffix of
.B k
multiplies the number by 1024. The pattern match stack is used to save
backtracking and conditional assignment information.  If your program
terminates with an \*(lqOverflow during pattern matching\*(rq message
you need to increase the pattern match stack size.

.SH SEE ALSO
.IP [1]
R. E. Griswold, J. F. Poage, and I. P. Polonsky
.IR "The SNOBOL4 Programming Language" ,
2nd ed., Prentice-Hall Inc., 1971.
.IP [2]
R. E. Griswold,
.IR "The Macro Implementation of SNOBOL4" ,
W. H. Freeman and Co., 1972.

.SH AUTHOR
Philip L. Budne

.SH BUGS
.PP
I/O retains some record oriented flavor.
.PP
I/O is still tied to unit numbers.
.PP
\*(lqDynamic\*(rq storage cannot be expanded after startup.
