.\" -*-nroff-*-
.\" $Id$
.ie n \{\
.       ds lq \&"\"
.       ds rq \&"\"
.\}
.el \{\
.       ds rq ''
.       ds lq ``
.\}
.TH SNOLIB 3 "04 Dec 2005" "Local"
.SH NAME
snolib \- SNOBOL4 library routines
.SH SYNOPSIS
.BI "-INCLUDE '" filename.sno "'"
.SH DESCRIPTION
.PP

The following
.BR snobol4 (1)
library routines are installed in
/usr/local/lib/snobol4 (the default path for -INCLUDE);

.TP
bq.sno
run a program in a subprocess and capture all output

.TP
chars.sno
defines a variable for each non-printing character
in the local character set

.TP
dynamic.sno
functions to compile and link dynamicly LOADable extensions.

.TP
fence.sno, not.sno, unique.sno
Emulation of SPITBOL FENCE() and NOT() functions, and unique
variable creation support routine, thanks to Peter-Arno Coppen

.TP
host.sno
Function codes for HOST() function

.TP
logic.sno
Prototypes for Catspaw Macro SPITBOL compatible LOGIC() function

.TP
ndbm.sno
Prototypes and values for SNOBOL4 NDBM Database Access routines, see
.BR snobol4dbm (3).

.TP
serv.sno
Example TCP server program

.TP
smtp.sno
Example code to send mail via TCP/SMTP

.TP
snobol4+.sno
SNOBOL4+ emulation functions:
ENVIRONMENT(), EXECUTE(), TELL(), SEEK()

.TP
spitbol.sno
SPITBOL emulation functions:
INPUT(), OUTPUT(), ENDFILE(), REWIND()

.TP
stcl.sno
Prototypes and values for SNOBOL4 Tcl/Tk routines, see
.BR snobol4tcl (3).

.TP
tcp.sno
TCP connection routines, used by the URL library (below)

.TP
url.sno, file.sno, ftp.sno, http.sno
Internet URL file reading support (for file, ftp and http URL's)

.TP
utf.sno
Experimental routines for handling UTF encoded (Unicode) data

.TP
wrapper.sno
Routines for creating C code wrappers for dynamicly loading code.

.SH SEE ALSO
.BR snobol4 (1)

.SH AUTHOR
Philip Budne
.br
Peter-Arno Coppen

.SH BUGS
This man page should describe how to use the routines,
but for now just tells you the files exist (which is better
than nothing).
