#!/bin/sh
# $Id$
# Test a combination of include/code/libs ~sigh~
# Phil Budne
# January 2, 2012

# XXX options to enable output, run program?

INCLUDES="$1"
BODY="$2"
LIBS="$3"

TMP=/tmp/check$$
TMP_C=${TMP}.c
trap "rm -f $TMP $TMP_C" 0

rm -f $TMP $TMP_C
for I in $INCLUDES; do
    echo "#include <$I>" >> $TMP_C
done
echo "int main(int argc, char *argv[]) {" >> $TMP_C
echo "    $BODY;"	>> $TMP_C
echo "    return 0;"	>> $TMP_C
echo "}"		>> $TMP_C

${CC:-cc} $CFLAGS -o $TMP $TMP_C $LIBS >/dev/null 2>&1
